# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="The command-line interface for Cabal and Hackage."
HOMEPAGE="http://www.haskell.org/cabal/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.10.1
		<dev-haskell/cabal-1.11
		>=dev-haskell/http-4000.0.2
		<dev-haskell/http-4001
		>=dev-haskell/network-1
		<dev-haskell/network-3
		>=dev-haskell/time-1.1
		<dev-haskell/time-1.3
		>=dev-haskell/zlib-0.4
		<dev-haskell/zlib-0.6
		>=dev-lang/ghc-6.10.1"
