# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Parallel Primitives for Data-Parallel Haskell."
HOMEPAGE="http://www.haskell.org/haskellwiki/GHC/Data_Parallel_Haskell"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/dph-base-0.5*
		=dev-haskell/dph-prim-interface-0.5*
		=dev-haskell/dph-prim-seq-0.5*
		>=dev-haskell/vector-0.7
		>=dev-lang/ghc-6.12.3"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

src_prepare() {
    sed -i -e 's/vector.*==.*0\.7\.\*/vector >= 0.7/' "${S}/${PN}.cabal"
}
