# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="A set of high-level concurrency utilities built on Communicating Haskell Processes"
HOMEPAGE="http://www.cs.kent.ac.uk/projects/ofa/chp/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/chp-2.2*
		=dev-haskell/deepseq-1.1*
		dev-haskell/hunit
		>=dev-haskell/quickcheck-2
		dev-haskell/stm
		>=dev-lang/ghc-6.10.4"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2.3"
