# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Example programs using the Yesod Web Framework."
HOMEPAGE="http://www.yesodweb.com/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6
		>=dev-haskell/data-object-0.3.1
		<dev-haskell/data-object-0.4
		>=dev-haskell/data-object-yaml-0.3.0
		<dev-haskell/data-object-yaml-0.4
		dev-haskell/hamlet
		dev-haskell/persistent-sqlite
		dev-haskell/persistent-template
		dev-haskell/stm
		dev-haskell/text
		>=dev-haskell/transformers-0.2.1
		<dev-haskell/transformers-0.3
		=dev-haskell/yesod-0.8*
		dev-haskell/yesod-form
		dev-haskell/yesod-static
		>=dev-lang/ghc-6.10.1"
