# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.14

EAPI=4

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A classical web server on WAI/warp"
HOMEPAGE="http://www.mew.org/~kazu/proj/mighttpd/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6
		dev-haskell/deepseq
		dev-haskell/hashmap
		dev-haskell/http-conduit
		dev-haskell/http-date
		dev-haskell/http-types
		dev-haskell/network
		>=dev-haskell/parsec-3
		dev-haskell/time
		dev-haskell/transformers
		dev-haskell/unix-bytestring
		dev-haskell/wai
		dev-haskell/wai-app-file-cgi
		dev-haskell/wai-logger-prefork
		dev-haskell/warp
		>=dev-lang/ghc-6.10.1"
