# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Manage sandboxed Haskell build environments"
HOMEPAGE="https://github.com/creswick/cabal-dev"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.10.0.0
		<dev-haskell/cabal-1.13
		>=dev-haskell/http-4000.0.9
		<dev-haskell/http-4000.2
		>=dev-haskell/mtl-1.1
		<dev-haskell/mtl-2.1
		>=dev-haskell/network-2.2
		<dev-haskell/network-2.4
		=dev-haskell/tar-0.3*
		=dev-haskell/transformers-0.2*
		=dev-haskell/zlib-0.5*
		>=dev-lang/ghc-6.10.1
		unknown-build-tool/cabal"
