# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin lib profile haddock hscolour"
inherit git-2 haskell-cabal

DESCRIPTION="Client library for the Redis datastore: supports full command set,
pipelining."
HOMEPAGE="http://hackage.haskell.org/package/hedis"
EGIT_REPO_URI="git://github.com/informatikr/hedis.git"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/attoparsec-0.10*
		=dev-haskell/bytestring-lexing-0.2*
		=dev-haskell/mtl-2*
		=dev-haskell/network-2*
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
